name: NGINX One Console Workflow Example
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ] 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  workaround_github_duplicate_actions_bug:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.0
        with:
          skip_after_successful_duplicate: 'true'

  run-n1c-python-example-script:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Checkout and set misc environment variables 
      run: |
        echo "MY_COMMIT_HASH=$(git show --pretty=format:"%H %s" -s HEAD)" >> $GITHUB_ENV
        echo "MY_BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
          
    - name: Set environment variables for base64 encoded config files
      run: |
        echo "NGINX_CONFIG_FILE=`echo \# Modified by https://github.com/bwolmarans/GitOps-NGINX-One $(date) branch: ${{ env.MY_BRANCH }} commit hash: ${{ env.MY_COMMIT_HASH }} | cat - app-nyc-02/etc/nginx/nginx.conf | base64 -w 0`" >> $GITHUB_ENV
        echo "MIME_TYPES_CONFIG_FILE=`cat app-nyc-02/etc/nginx/mime.types | base64 -w 0`" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install PIP requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run the n1c Python script
      run: |
        python nginx_one_console_api_python_example.py --n1c_tenant_fqdn=${{ vars.N1C_TENANT_FQDN }} --n1c_namespace=${{ vars.N1C_NAMESPACE}} --nginx_instance_hostname=${{ vars.NGINX_INSTANCE_HOSTNAME}} --nginx_instance_id=${{ vars.NGINX_INSTANCE_ID }} --xc_api_token=${{ secrets.XC_API_TOKEN }} --nginx_config_file=${{ env.NGINX_CONFIG_FILE }}
      
